//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernIconLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernIconLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DetailDataView_16x {
            get {
                object obj = ResourceManager.GetObject("DetailDataView_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] FluentSystemIcons_Filled {
            get {
                object obj = ResourceManager.GetObject("FluentSystemIcons_Filled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///F101,access_time,,
        ///E002,accessibility,,
        ///F00C,accessibility_checkmark,,
        ///F05CB,accessibility_error,,
        ///F06C6,accessibility_more,,
        ///F05CD,accessibility_question_mark,,
        ///F5A3,add,,
        ///F0747,add_circle,,
        ///F01E5,add_square,,
        ///F0279,add_square_multiple,,
        ///F0960,add_starburst,,
        ///E00E,add_subtract_circle,,
        ///F0870,agents,,
        ///F0A50,agents_add,,
        ///F070B,airplane,,
        ///E0EF,airplane_landing,,
        ///F113,airplane_take_off,,
        ///E010,album,,
        ///E012,album_add,,
        ///E016,alert,,
        ///F0871,alert_badge,,
        ///F11A,alert_off, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FluentSystemIcons_Filled_codepoints {
            get {
                return ResourceManager.GetString("FluentSystemIcons_Filled_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] FluentSystemIcons_Regular {
            get {
                object obj = ResourceManager.GetObject("FluentSystemIcons_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///F101,access_time,,
        ///E002,accessibility,,
        ///F00C,accessibility_checkmark,,
        ///F0552,accessibility_error,,
        ///F064A,accessibility_more,,
        ///F0554,accessibility_question_mark,,
        ///F598,add,,
        ///F06CA,add_circle,,
        ///F01E5,add_square,,
        ///F0266,add_square_multiple,,
        ///F08E3,add_starburst,,
        ///E00E,add_subtract_circle,,
        ///F07F3,agents,,
        ///F09D3,agents_add,,
        ///F0690,airplane,,
        ///E0EF,airplane_landing,,
        ///F113,airplane_take_off,,
        ///E010,album,,
        ///E012,album_add,,
        ///E016,alert,,
        ///F07F4,alert_badge,,
        ///F11A,alert_off, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FluentSystemIcons_Regular_codepoints {
            get {
                return ResourceManager.GetString("FluentSystemIcons_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_7_Brands_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_7_Brands_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_7_Free_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_7_Free_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_7_Free_Solid_900 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_7_Free_Solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///f368,Accessible Icon,Accessibility,accessibility;disabled;handicap;person;uer;wheelchair;wheelchair-alt
        ///f368,Accessible Icon,Medical + Health,accessibility;disabled;handicap;person;uer;wheelchair;wheelchair-alt
        ///f368,Accessible Icon,Transportation,accessibility;disabled;handicap;person;uer;wheelchair;wheelchair-alt
        ///f368,Accessible Icon,Users + People,accessibility;disabled;handicap;person;uer;wheelchair;wheelchair-alt
        ///f642,Alipay,Shopping,
        ///f42c,Amazon Pay,Shopping,
        ///f415,Apple P [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome7Brands_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome7Brands_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///f2b9,Address Book,Business,contact;directory;employee;index;little black book;portfolio;rolodex;uer;username
        ///f2b9,Address Book,Communication,contact;directory;employee;index;little black book;portfolio;rolodex;uer;username
        ///f2b9,Address Book,Users + People,contact;directory;employee;index;little black book;portfolio;rolodex;uer;username
        ///f2bb,Address Card,Accessibility,about;contact;employee;id;identification;portfolio;postcard;profile;registration;uer;username
        ///f2bb,Address Card,A [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome7Regular_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome7Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///30,0,Numbers,Digit Zero;nada;none;zero;zilch
        ///31,1,Numbers,Digit One;one
        ///32,2,Numbers,Digit Two;two
        ///33,3,Numbers,Digit Three;three
        ///34,4,Numbers,Digit Four;four
        ///35,5,Numbers,Digit Five;five
        ///36,6,Numbers,Digit Six;six
        ///37,7,Numbers,Digit Seven;seven
        ///38,8,Numbers,Digit Eight;eight
        ///39,9,Numbers,Digit Nine;nine
        ///41,A,Alphabet,Latin Capital Letter A;Latin Small Letter A;letter
        ///f2b9,Address Book,Business,contact;directory;employee;index;little black book;portfolio;rolodex;uer;usern [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome7Solid_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome7Solid_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Grid_16x {
            get {
                object obj = ResourceManager.GetObject("Grid_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIcons_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIcons_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e951,10k,,
        ///e952,10mp,,
        ///e953,11mp,,
        ///eb8d,123,,
        ///e954,12mp,,
        ///e955,13mp,,
        ///e956,14mp,,
        ///e957,15mp,,
        ///e958,16mp,,
        ///e959,17mp,,
        ///f8fd,18_up_rating,,
        ///e95a,18mp,,
        ///e95b,19mp,,
        ///e95c,1k,,
        ///e95d,1k_plus,,
        ///efcd,1x_mobiledata,,
        ///e95e,20mp,,
        ///e95f,21mp,,
        ///e960,22mp,,
        ///e961,23mp,,
        ///e962,24mp,,
        ///e963,2k,,
        ///e964,2k_plus,,
        ///e965,2mp,,
        ///efce,30fps,,
        ///efcf,30fps_select,,
        ///e577,360,,
        ///e84d,3d_rotation,,
        ///efd0,3g_mobiledata,,
        ///e966,3k,,
        ///e967,3k_plus,,
        ///e968,3mp,,
        ///efd1,3p,,
        ///efd2,4g_mobiledata,, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIcons_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIcons_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsOutlined_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsOutlined_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsOutlined_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsOutlined_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsRound_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsRound_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsRound_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsRound_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsSharp_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsSharp_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsSharp_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsSharp_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pictgrammers_materialdesignicons {
            get {
                object obj = ResourceManager.GetObject("Pictgrammers_materialdesignicons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///F01C9,ab-testing,,
        ///F16E0,abacus,,
        ///F1328,abjad-arabic,,
        ///F1329,abjad-hebrew,,
        ///F132A,abugida-devanagari,,
        ///F132B,abugida-thai,,
        ///F0003,access-point,,
        ///F1538,access-point-check,,
        ///F1539,access-point-minus,,
        ///F0002,access-point-network,,
        ///F0BE1,access-point-network-off,,
        ///F1511,access-point-off,,
        ///F153A,access-point-plus,,
        ///F153B,access-point-remove,,
        ///F0004,account,,
        ///F0005,account-alert,,
        ///F0B50,account-alert-outline,,
        ///F1868,account-arrow-down,,
        ///F1869,account-arrow-down-outline,, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pictgrammers_Regular_codepoints {
            get {
                return ResourceManager.GetString("Pictgrammers_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16x {
            get {
                object obj = ResourceManager.GetObject("Refresh_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///E700,GlobalNavigationButton,,
        ///E701,Wifi,,
        ///E702,Bluetooth,,
        ///E703,Connect,,
        ///E704,InternetSharing,,
        ///E705,VPN,,
        ///E706,Brightness,,
        ///E707,MapPin,,
        ///E708,QuietHours,,
        ///E709,Airplane,,
        ///E70A,Tablet,,
        ///E70B,QuickNote,,
        ///E70C,RememberedDevice,,
        ///E70D,ChevronDown,,
        ///E70E,ChevronUp,,
        ///E70F,Edit,,
        ///E710,Add,,
        ///E711,Cancel,,
        ///E712,More,,
        ///E713,Setting,,
        ///E714,Video,,
        ///E715,Mail,,
        ///E716,People,,
        ///E717,Phone,,
        ///E718,Pin,,
        ///E719,Shop,,
        ///E71A,Stop,,
        ///E71B,Link,,
        ///E71C,Filter,,
        ///E71D,AllApps,,
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SegoeMDL2Assets_codepoints {
            get {
                return ResourceManager.GetString("SegoeMDL2Assets_codepoints", resourceCulture);
            }
        }
    }
}
