//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernIconLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernIconLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DetailDataView_16x {
            get {
                object obj = ResourceManager.GetObject("DetailDataView_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_6_Brands_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Brands_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_6_Free_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Free_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Font_Awesome_6_Free_Solid_900 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Free_Solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e080,42.group,,
        ///f26e,500px,,
        ///f368,Accessible Icon,Accessibility;Medical + Health;Transportation;Users + People,
        ///f369,Accusoft,,
        ///f170,App.net,,
        ///f36a,Adversal,,
        ///f36b,affiliatetheme,,
        ///f834,Airbnb,,
        ///f36c,Algolia,,
        ///f642,Alipay,Shopping,
        ///f270,Amazon,,
        ///f42c,Amazon Pay,Shopping,
        ///f36d,Amilia,,
        ///f17b,Android,,
        ///f209,AngelList,,
        ///f36e,Angry Creative,,
        ///f420,Angular,,
        ///f36f,App Store,,
        ///f370,iOS App Store,,
        ///f371,Apper Systems AB,,
        ///f179,Apple,,
        ///f415,Apple Pay,Shopping,
        ///f77a,Artst [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome6Brands_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome6Brands_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///f2b9,Address Book,Business;Communication;Users + People,
        ///f2bb,Address Card,Business;Communication;Users + People,
        ///f0f3,bell,Alert;Education;Household;Maps;Shopping;Social;Time,
        ///f1f6,Bell Slash,Alert;Education;Maps;Time,
        ///f02e,bookmark,Maps;Shapes;Shopping;Writing,
        ///f1ad,Building,Buildings;Business;Humanitarian;Maps,
        ///f133,Calendar,Business;Shapes;Time,
        ///f274,Calendar Check,Time,
        ///f073,Calendar Days,Business;Time,
        ///f272,Calendar Minus,Time,
        ///f271,Calendar Plus,Time,
        ///f273,Calendar [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome6Regular_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome6Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///30,0,Numbers,
        ///31,1,Numbers,
        ///32,2,Numbers,
        ///33,3,Numbers,
        ///34,4,Numbers,
        ///35,5,Numbers,
        ///36,6,Numbers,
        ///37,7,Numbers,
        ///38,8,Numbers,
        ///39,9,Numbers,
        ///41,A,Alphabet,
        ///f037,align-center,Text Formatting,
        ///f039,align-justify,Text Formatting,
        ///f036,align-left,Text Formatting,
        ///f038,align-right,Text Formatting,
        ///f13d,Anchor,Humanitarian;Logistics;Maps;Maritime,
        ///e4aa,Anchor Circle-check,Humanitarian;Logistics;Maritime,
        ///e4ab,Anchor Circle-exclamation,Humanitarian;Logistics;Maritime,
        ///e4ac [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_Awesome6Solid_codepoints {
            get {
                return ResourceManager.GetString("Font_Awesome6Solid_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Grid_16x {
            get {
                object obj = ResourceManager.GetObject("Grid_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIcons_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIcons_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e951,10k,,
        ///e952,10mp,,
        ///e953,11mp,,
        ///eb8d,123,,
        ///e954,12mp,,
        ///e955,13mp,,
        ///e956,14mp,,
        ///e957,15mp,,
        ///e958,16mp,,
        ///e959,17mp,,
        ///f8fd,18_up_rating,,
        ///e95a,18mp,,
        ///e95b,19mp,,
        ///e95c,1k,,
        ///e95d,1k_plus,,
        ///efcd,1x_mobiledata,,
        ///e95e,20mp,,
        ///e95f,21mp,,
        ///e960,22mp,,
        ///e961,23mp,,
        ///e962,24mp,,
        ///e963,2k,,
        ///e964,2k_plus,,
        ///e965,2mp,,
        ///efce,30fps,,
        ///efcf,30fps_select,,
        ///e577,360,,
        ///e84d,3d_rotation,,
        ///efd0,3g_mobiledata,,
        ///e966,3k,,
        ///e967,3k_plus,,
        ///e968,3mp,,
        ///efd1,3p,,
        ///efd2,4g_mobiledata,, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIcons_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIcons_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsOutlined_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsOutlined_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsOutlined_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsOutlined_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsRound_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsRound_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsRound_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsRound_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] MaterialIconsSharp_Regular {
            get {
                object obj = ResourceManager.GetObject("MaterialIconsSharp_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///e14d,content_copy,,
        ///e14e,content_cut,,
        ///e14f,content_paste,,
        ///f08a,copy,,
        ///f08b,cut,,
        ///f008,face_unlock,,
        ///ec31,fluorescent,,
        ///e249,format_underline,,
        ///e249,format_underlined,,
        ///e5d3,keyboard_control,,
        ///f21b,leave_bags_at_home,,
        ///e5d3,more_horiz,,
        ///e1bc,now_wallpaper,,
        ///e1bd,now_widgets,,
        ///f098,paste,,
        ///e1bc,wallpaper,,
        ///e1bd,widgets,,
        ///ead9,wifi_tethering_error,,
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaterialIconsSharp_Regular_codepoints {
            get {
                return ResourceManager.GetString("MaterialIconsSharp_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pictgrammers_materialdesignicons {
            get {
                object obj = ResourceManager.GetObject("Pictgrammers_materialdesignicons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Code,Name,Category,Tags
        ///F01C9,ab-testing,,
        ///F16E0,abacus,,
        ///F1328,abjad-arabic,,
        ///F1329,abjad-hebrew,,
        ///F132A,abugida-devanagari,,
        ///F132B,abugida-thai,,
        ///F0003,access-point,,
        ///F1538,access-point-check,,
        ///F1539,access-point-minus,,
        ///F0002,access-point-network,,
        ///F0BE1,access-point-network-off,,
        ///F1511,access-point-off,,
        ///F153A,access-point-plus,,
        ///F153B,access-point-remove,,
        ///F0004,account,,
        ///F0005,account-alert,,
        ///F0B50,account-alert-outline,,
        ///F1868,account-arrow-down,,
        ///F1869,account-arrow-down-outline,, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pictgrammers_Regular_codepoints {
            get {
                return ResourceManager.GetString("Pictgrammers_Regular_codepoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16x {
            get {
                object obj = ResourceManager.GetObject("Refresh_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
